### ISSUE TITLE
IC2 Type Support

### ISSUE THREAD

**Issue by Speiger** [hilburn/NotEnoughResources#54]
I've got an issue for IC2 Classic that your mod throws a exception with classic.
https://github.com/TinyModularThings/IC2Classic/issues/83#issuecomment-122224933
Problem is that you are searching for IC2 Exp classes that do not exist in classic.
I could make a fake config that provides most information to your mod but that could cause some serious trouble with your mod. Thats why i am asking for support from your side.
IC2 Classic API (simply source from the githubpage i posted here) is there, you can detect in the (ic2/api/info/IC2Classic.class) if IC2 Classic is loaded. At the moment i am using only the IC2 ModID but i planned with the next update to do some parts there^^

If there is anything else i could help with just ask.

Thanks for reading. Speiger

**Comment by way2muchnoise** [comment]
My guess would be you have the same modID which you shouldn't. The IC2 compat gets triggered by the ID ```IC2```
https://github.com/hilburn/NotEnoughResources/blob/master/src/main/java/neresources/utils/ModList.java#L91

**Comment by Speiger** [comment]
Yeah i have to do that else addons of IC2 would not get loaded. And Classic joins with Exp Addon support.^^" That is the reason why i do it.

**Comment by Speiger** [comment]
Anyway you can detect the differend types with this class at the moment. If you detect the api it might be possible that the Classic version is loaded. And then you still can check that.^^
https://github.com/TinyModularThings/IC2Classic/blob/master/ic2/api/info/IC2Classic.java#L32

**Comment by Speiger** [comment]
@way2muchnoise sadly i am forced to use the IC2 Modid because IC2 Classic is IC2 and should also load the IC2 Plugins. Anyways since you are requesting Core Classes from Exp which classic does not have you should then make a filter/checking system that checks which IC2 is loaded because avoding the Crash will be some kind hard without a so dirty fix that it is not worth making it...

So please make a checking system which IC2 is loaded. API from my side is provided which tells you that.

**Comment by hilburn** [comment]
It is fixed - NER compat is disabled if the IC2 version is non-exp, if you want to re-enabled it, we have a very extensive message system to allow you to register whatever the hell you like

**Comment by Speiger** [comment]
Thanks^^" is there any way to register nessesary information?
Because support for it should stay at least^^"

**Comment by hilburn** [comment]
https://github.com/hilburn/NotEnoughResources/blob/master/src/main/java/neresources/api/messages/RegisterOreMessage.java

**Comment by Speiger** [comment]
Ok. Thanks i will write an Plugin for that so that everything nessesary gets loaded for your mod if it is there^^"

**Comment by Speiger** [comment]
@hilburn still not fixed. NER still crashes with IC2 Classic. Reason beeing that you use the IC2ID to remove the Exp code. Since Exp has not a second modID that is not shared with classic you need to find another way. (Did ask a exp dev to implement a second modID)
